spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/lyfe
    username: root
    password: asdf1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

server:
  tomcat:
    basedir: tomcat

management:
  endpoints:
    enabled-by-default: false

environment: local