package initTest.lyfe.lyfeBe.test.mock

import lyfe.lyfeBe.user.User
import lyfe.lyfeBe.user.port.out.UserPort
import java.util.*
import java.util.concurrent.atomic.AtomicLong

class FakeUserRepository : UserPort {
    private val autoGeneratedId = AtomicLong(0)
    private val data: MutableList<User> = Collections.synchronizedList(ArrayList())


    override fun create(user: User): User {
        val newUser = user.copy(id = autoGeneratedId.incrementAndGet())
        data.add(newUser)
        return newUser
    }

    override fun findById(userId: Long) = data.find { it.id == userId }

    override fun getByIdAndValidateActive(id: Long): User {
        TODO("Not yet implemented")
    }

    override fun getById(userId: Long) = data.find { it.id == userId }!!


}
