package initTest.lyfe.lyfeBe.test.mock

import lyfe.lyfeBe.report.Report
import lyfe.lyfeBe.report.ReportTarget
import lyfe.lyfeBe.report.port.out.ReportPort
import org.springframework.data.domain.Pageable
import java.time.Instant
import java.util.*
import java.util.concurrent.atomic.AtomicLong

class FakeReportRepository: ReportPort {

    private val autoGeneratedId = AtomicLong(0)
    private val data: MutableList<Report> = Collections.synchronizedList(ArrayList())
    override fun create(report: Report): Report {
        val id = autoGeneratedId.incrementAndGet()
        val newReport = report.copy(
            id = id,
            createdAt = Instant.now()
        )
        data.add(newReport)
        return newReport
    }

    override fun update(report: Report): Report {
        data.removeIf { it.id == report.id }
        data.add(report)
        return report
    }

    override fun getById(reportId: Long): Report {
        return data.find { it.id == reportId }?: throw NoSuchElementException()
    }

    override fun getByUserIdAndReportTargetIdAndReportTarget(
        userId: Long,
        reportTargetId: Long,
        reportTarget: ReportTarget
    ): Report? {
        return data.find { it.reportedUser.id == userId && it.reportTargetId == reportTargetId && it.reportTarget == reportTarget }
    }

    override fun getReportedCount(reportTargetId: Long): Int {
        return data.count { it.reportTargetId == reportTargetId }
    }

    override fun getReportsWithCursor(cursorId: Long, pageable: Pageable): List<Report> {
        val report = data.filter { it.id < cursorId }.sortedByDescending { it.id }

        val pageSize = pageable.pageSize
        val offset = pageable.offset.toInt()
        val toIndex = (offset + pageSize).coerceAtMost(report.size)

        return if (offset < report.size) report.subList(offset, toIndex) else emptyList()
    }

    override fun cancel(report: Report): Report {
        data.find { it.id == report.id } ?: throw NoSuchElementException("Report not found with id: $report.id")
        val updatedReport = report.copy(
            isCanceled = !report.isCanceled, // 토글
            canceledAt = if (report.isCanceled) null else Instant.now()
        )
        data.removeIf { it.id == updatedReport.id }
        data.add(updatedReport)
        return updatedReport
    }

    fun clear() {
        data.clear()
    }
}