package initTest.lyfe.lyfeBe.test.mock

import lyfe.lyfeBe.topic.Topic
import lyfe.lyfeBe.whisky.Whisky
import lyfe.lyfeBe.whisky.out.WhiskyPort
import java.util.*
import java.util.concurrent.atomic.AtomicLong

class FakeWhiskyRepository : WhiskyPort {
    private val autoGeneratedId = AtomicLong(0)
    private val data: MutableList<Whisky> = Collections.synchronizedList(ArrayList())


    override fun countByBoardId(boardId: Long) = 1

    override fun create(whisky: Whisky): Whisky {
        return if (whisky.id == 0L) {
            val newWhisky = whisky.copy(id = autoGeneratedId.incrementAndGet())
            data.add(newWhisky)
            newWhisky
        } else {
            data.removeIf { it.id == whisky.id }
            data.add(whisky)
            whisky
        }
    }

    fun clear() {
        data.clear()
    }
}
