package initTest.lyfe.lyfeBe.test.mock

import lyfe.lyfeBe.whisky.Whisky
import lyfe.lyfeBe.whisky.out.WhiskyPort
import java.util.*
import java.util.concurrent.atomic.AtomicLong

class FakeWhiskyRepository : WhiskyPort {
    private val autoGeneratedId = AtomicLong(0)
    private val data: MutableList<Whisky> = Collections.synchronizedList(ArrayList())


    override fun countByBoardId(boardId: Long): Int {
        return data.count { it.board.id == boardId }
    }

    override fun create(whisky: Whisky): Whisky {
        return if (whisky.id == 0L) {
            val newWhisky = whisky.copy(id = autoGeneratedId.incrementAndGet())
            data.add(newWhisky)
            newWhisky
        } else {
            data.removeIf { it.id == whisky.id }
            data.add(whisky)
            whisky
        }
    }

    override fun update(boardId: Long) {
        TODO("Not yet implemented")
    }

    override fun assertNoExistingWhisky(boardId: Long, userId: Long) =
        data.find {
            it.board.id == boardId && it.user.id == userId
        }

    override fun delete(boardId: Long, userId: Long) {
        data.removeIf { it.board.id == boardId && it.user.id == userId }
    }

    fun clear() {
        data.clear()
    }

    override fun get(whiskyId: Long) = data.find { it.id == whiskyId }!!
}
