package initTest.lyfe.lyfeBe.test.mock

import lyfe.lyfeBe.feedback.Feedback
import lyfe.lyfeBe.feedback.port.out.FeedBackPort
import java.util.*
import java.util.concurrent.atomic.AtomicLong

class FakeFeedBackRepository : FeedBackPort {

    private val autoGeneratedId = AtomicLong(0)
    private val data: MutableList<Feedback> = Collections.synchronizedList(ArrayList())

    override fun create(feedBack: Feedback): Feedback {
        return if (feedBack.id == 0L) {
            val newFeedback = feedBack.copy(id = autoGeneratedId.incrementAndGet())
            data.add(newFeedback)
            newFeedback
        } else {
            data.removeIf { it.id == feedBack.id }
            data.add(feedBack)
            feedBack
        }    }

    override fun getById(id: Long): Feedback {
        return data.find { it.id == id }!!
    }


    fun clear() {
        data.clear()
    }


}