package lyfe.lyfeBe.test.mock

import lyfe.lyfeBe.policy.Policy
import lyfe.lyfeBe.policy.PolicyType
import lyfe.lyfeBe.policy.out.PolicyPort
import java.util.*
import java.util.concurrent.atomic.AtomicLong

class FakePolicyRepository : PolicyPort {

    private val autoGeneratedId = AtomicLong(0)
    private val data: MutableList<Policy> = Collections.synchronizedList(ArrayList())

    override fun getPolicy(type: PolicyType): Policy {
        TODO("Not yet implemented")
    }

    override fun create(policy: Policy): Policy {
        TODO("Not yet implemented")
    }

    override fun findById(id: Long): Policy {
        TODO("Not yet implemented")
    }

    override fun update(policy: Policy): Policy {
        TODO("Not yet implemented")
    }

    fun clear() {
        data.clear()
    }


}